# NumPy Indexing and Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 10+1)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[8]

8

In [4]:
arr[1:5]

array([1, 2, 3, 4])

In [5]:
arr[:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [6]:
arr = np.arange(0, 10+1)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
slice_of_array = arr[0:5] # getting referenced
slice_of_array

array([0, 1, 2, 3, 4])

In [8]:
slice_of_array[:] = 99
slice_of_array

array([99, 99, 99, 99, 99])

In [9]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [10]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [11]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [12]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [13]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [14]:
arr_2d[0]

array([ 5, 10, 15])

In [15]:
arr_2d[1][1]

25

In [16]:
arr_2d[1, 2]

30

In [17]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [18]:
arr = np.arange(0, 10+1)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
bool_array = arr > 5
bool_array

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [20]:
arr[bool_array]

array([ 6,  7,  8,  9, 10])

In [21]:
arr_2d = np.arange(50).reshape(5, 10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [22]:
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])